"""
crab.templates — built-in crab.yaml template strings.

Exposed via ``crabctl init-config``.
"""

# ---------------------------------------------------------------------------
# Minimal template
# ---------------------------------------------------------------------------

CONFIG_TEMPLATE_MINIMAL = """\
# crab.yaml — minimal working configuration
# Generated by: crabctl init-config --minimal
#
# Loads IGTF certificates from an existing local directory and writes
# an OpenSSL CApath directory.  Adjust paths for your environment.

version: 1

sources:
  igtf:
    type: igtf
    path: /etc/grid-security/certificates

profiles:
  grid:
    sources: [igtf]
    output_path: /etc/grid-security/certificates-crab
    atomic: true
    rehash: auto
    policy:
      reject_expired: true
      require_ca_flag: true
"""

# ---------------------------------------------------------------------------
# Full annotated template
# ---------------------------------------------------------------------------

CONFIG_TEMPLATE_FULL = """\
##
## crab.yaml — full annotated configuration reference
## Generated by: crabctl init-config
##
## Copy this file, remove sections you don't need, and adjust paths.
## String values support environment variable interpolation:
##   ${VAR}           — required variable (error if unset)
##   ${VAR:-default}  — optional variable with fallback value
##
## Editor autocompletion (VS Code / neovim yaml-language-server):
##   # yaml-language-server: $schema=https://raw.githubusercontent.com/snafus/crab-certbundle/main/crab/schema/config.schema.json

version: 1

# ---------------------------------------------------------------------------
# Sources — where to load CA certificates from
# ---------------------------------------------------------------------------
sources:

  # IGTF trust anchors from a local directory (typical on an existing grid node)
  igtf-classic-dir:
    type: igtf
    path: /etc/grid-security/certificates
    # Restrict to specific IGTF policy distributions.
    # Values: classic, iota, mics, slcs.  Omit to accept all.
    policies:
      - classic
      - iota

  # IGTF trust anchors fetched directly from dl.igtf.net over HTTPS
  igtf-online:
    type: igtf
    url: "https://dl.igtf.net/distribution/igtf/current/accredited/igtf-preinstalled-bundle-classic-1.120.tar.gz"
    cache_dir: "${CRAB_CACHE_DIR:-/var/cache/crab}"
    policies:
      - classic

  # IGTF trust anchors from a downloaded tarball
  igtf-tarball:
    type: igtf
    tarball: /var/cache/crab/igtf-preinstalled-bundle-classic-1.120.tar.gz
    policies:
      - classic

  # Public CA roots from the OS trust store.
  # Auto-detected on EL, Debian/Ubuntu, Alpine, and macOS.
  # Override path: if your bundle is in a non-standard location.
  system-roots:
    type: system
    # path: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

  # Local PEM files or directory
  custom-roots:
    type: local
    path: /etc/crab/extra-roots/
    pattern:
      - "*.pem"
      - "*.crt"
    recursive: false


# ---------------------------------------------------------------------------
# Output profiles — one profile = one output directory (or file)
# ---------------------------------------------------------------------------
profiles:

  # Classic IGTF-only trust directory for grid software (XRootD, dCache, gfal2, …)
  grid:
    description: "IGTF classic + IOTA trust anchors for grid data transfer"
    sources:
      - igtf-classic-dir
    output_path: /etc/grid-security/certificates
    staging_path: /var/lib/crab/staging/grid

    # Write atomically: stage in a temp directory, then rename into place.
    atomic: true

    # rehash: "auto"    → try openssl rehash, then builtin
    #         "openssl" → require openssl rehash (fail if unavailable)
    #         "builtin" → pure-Python hash computation only
    rehash: auto

    # Copy IGTF .info / .signing_policy / .namespaces files alongside certs.
    include_igtf_meta: true

    # Fetch and store CRLs alongside the certificates.
    include_crls: true

    policy:
      reject_expired: true
      reject_not_yet_valid: false
      require_ca_flag: true

      # include: if present, a cert must match at least one rule to pass.
      # (No include rules = accept everything that passes structural checks.)
      # include:
      #   - igtf_policy: classic
      #   - igtf_policy: iota

      # exclude: matching certs are dropped silently.
      # exclude:
      #   - fingerprint_sha256: "AA:BB:CC:..."
      #   - subject_regex: "CN=Some Deprecated CA.*"

      # warn: matching certs pass through but are flagged as WARN.
      # WARN certs are counted toward --strict-warnings exit code 3.
      # warn:
      #   - subject_regex: "CN=Expiring Soon CA.*"

    # CRL settings (only active when include_crls: true)
    crl:
      fetch: true
      # Write CRLs to the same directory as the certificates.
      crl_path: /etc/grid-security/certificates
      max_age_hours: 24
      # Warn if a cached CRL's nextUpdate is closer than this many hours.
      min_remaining_hours: 4
      # Skip re-fetch if the cached CRL still has this many hours of life left.
      # Useful for CAs that publish weekly CRLs: set to e.g. 12.
      refetch_before_expiry_hours: 0
      verify_tls: true
      timeout_seconds: 30
      max_workers: 8
      sources:
        - distribution   # CDP extension in the certificate
        - igtf           # .crl_url from IGTF .info file

    file_mode: "0o644"
    dir_mode: "0o755"


  # Server-auth only: public CAs for validating server TLS certificates
  server-auth:
    description: "Public CA roots for server certificate validation"
    sources:
      - system-roots
      - custom-roots
    output_path: /etc/crab/server-auth
    staging_path: /var/lib/crab/staging/server-auth
    atomic: true
    rehash: auto
    include_igtf_meta: false
    include_crls: false

    policy:
      reject_expired: true
      require_ca_flag: true
      exclude:
        # Example: remove a specific CA by fingerprint
        # - fingerprint_sha256: "AA:BB:CC:DD:..."
        []

    file_mode: "0o644"
    dir_mode: "0o755"


  # PEM bundle: all trust anchors concatenated into a single file.
  # output_path must be a file path (not a directory).
  # trust-bundle-pem:
  #   description: "Concatenated PEM bundle"
  #   sources:
  #     - igtf-classic-dir
  #     - system-roots
  #   output_format: bundle
  #   output_path: /etc/crab/ca-bundle.pem
  #   policy:
  #     reject_expired: true
  #     require_ca_flag: true


  # PKCS#12 bundle: all trust anchors in a single .p12 file (Java, browsers, …)
  # output_path must be a file path (not a directory).
  # trust-bundle-p12:
  #   description: "All trust anchors as a PKCS#12 file"
  #   sources:
  #     - igtf-classic-dir
  #     - system-roots
  #   output_format: pkcs12
  #   output_path: /etc/crab/trust-bundle.p12
  #   pkcs12_password: "${PKCS12_PASSPHRASE:-}"
  #   policy:
  #     reject_expired: true
  #     require_ca_flag: true


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging:
  level: INFO    # DEBUG, INFO, WARNING, ERROR
  format: text   # text or json (one JSON object per line)
  # file: /var/log/crab.log
"""
