#!/bin/sh
# postrm for crab-certbundle
set -e

case "$1" in
    remove|purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        if [ -d /run/systemd/system ]; then
            systemctl --system daemon-reload >/dev/null 2>&1 || true
        fi
        ;;
    *)
        echo "postrm: unrecognised argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
exit 0
