#!/bin/sh
# prerm for crab-certbundle
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            systemctl stop  crabctl.timer   >/dev/null 2>&1 || true
            systemctl stop  crabctl.service >/dev/null 2>&1 || true
            systemctl disable crabctl.timer >/dev/null 2>&1 || true
        fi
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm: unrecognised argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
exit 0
